import { getStore } from '@netlify/blobs';
import { questions as staticQuestions } from '../../../data/questionData';
import { Question } from '../../../types';
import { decrypt } from './encryption';

const CUSTOM_QUESTIONS_KEY = 'custom_questions';

async function getCustomQuestions(): Promise<Question[]> {
  try {
    const store = getStore({
      name: 'cissp-vault',
      siteID: process.env.SITE_ID,
      token: process.env.BLOBS_TOKEN,
    });
    const raw = await store.get(CUSTOM_QUESTIONS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(decrypt(raw));
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

// Looks up a question's authoritative data (correct answer, difficulty)
// from the sources the server actually knows about: the bundled static
// bank and admin-added custom questions. Returns null for anything else --
// notably, questions dynamically generated by the Gemini "AI Studio" quiz
// engine are never persisted anywhere the server can see them, so they
// can't be independently verified this way. Callers should treat a null
// result as "unverifiable" and handle it accordingly (see grade_quiz.ts).
export async function getQuestionById(id: string): Promise<Question | null> {
  const staticMatch = staticQuestions.find(q => q.id === id);
  if (staticMatch) return staticMatch;

  const custom = await getCustomQuestions();
  const customMatch = custom.find(q => q.id === id);
  return customMatch || null;
}
